/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/f9rocket.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.01, 0, 0.02]} scale={[2.6, 2.6, 2.6]}>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.body_black} geometry={nodes.Circle_body_black_0.geometry}/>
        </group>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.engine} geometry={nodes.Circle001_engine_0.geometry} />
        </group>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.engine} geometry={nodes.Circle002_engine_0.geometry} />
        </group>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.engine} geometry={nodes.Circle003_engine_0.geometry} />
        </group>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.engine} geometry={nodes.Circle004_engine_0.geometry} />
        </group>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.engine} geometry={nodes.Circle005_engine_0.geometry} />
        </group>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.engine} geometry={nodes.Circle006_engine_0.geometry} />
        </group>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.engine} geometry={nodes.Circle007_engine_0.geometry} />
        </group>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.engine} geometry={nodes.Circle008_engine_0.geometry} />
        </group>
        <group position={[0, 0.19, 0]} rotation={[-Math.PI, 0, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.engine} geometry={nodes.Circle009_engine_0.geometry} />
        </group>
        <group position={[0, 6.01, 0]} rotation={[-0.06, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials.details} geometry={nodes.Cube_details_0.geometry} />
        </group>
        <group position={[0, 7.27, 0.27]} scale={[0.01, 0.01, 0]}>
          <mesh material={materials.details} geometry={nodes.Cube002_details_0.geometry} />
        </group>
        <group position={[0, 5.93, 0]} rotation={[0, Math.PI / 4, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.fins} geometry={nodes.Cube004_fins_0.geometry} />
        </group>
        <group position={[0, 0.24, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.body} geometry={nodes.Cylinder_body_0.geometry} />
          <mesh material={materials.body_black} geometry={nodes.Cylinder_body_black_0.geometry} />
        </group>
        <group position={[0, 8.48, 0]} rotation={[0, 1.57, 0]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.fairing} geometry={nodes.Cylinder001_fairing_0.geometry} />
        </group>
        <group position={[0.09, 7.2, 0.26]} rotation={[Math.PI / 2, 0, -0.3]} scale={[-0.01, -0.01, -0.01]}>
          <mesh material={materials.details} geometry={nodes.Plane_details_0.geometry} />
        </group>
        <group position={[0, 7.07, 0]} rotation={[Math.PI / 2, 0.02, -Math.PI / 2]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.details} geometry={nodes.Plane002_details_0.geometry} />
        </group>
        <group position={[-0.19, 8.12, 0.19]} rotation={[Math.PI / 2, 0, 0.78]} scale={[-0.01, -0.01, -0.01]}>
          <mesh material={materials.details} geometry={nodes.Plane003_details_0.geometry} />
        </group>
        <group position={[-0.02, 7.49, 0.27]} rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials.details} geometry={nodes.Plane004_details_0.geometry} />
        </group>
        <group position={[-0.25, 7.55, 0.1]} rotation={[Math.PI / 2, 0, 1.14]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials.details} geometry={nodes.Plane005_details_0.geometry} />
        </group>
        <group position={[0.27, 7.64, 0.01]} rotation={[Math.PI / 2, 0, -1.48]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials.details} geometry={nodes.Plane006_details_0.geometry} />
        </group>
        <group position={[0.27, 8.14, 0.01]} rotation={[Math.PI / 2, 0, -1.48]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials.details} geometry={nodes.Plane007_details_0.geometry} />
        </group>
        <group position={[-0.02, 7.87, -0.26]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.01, 0.01, 0.01]}>
          <mesh material={materials.details} geometry={nodes.Plane008_details_0.geometry} />
        </group>
        <group position={[0, 1.01, -0.03]} rotation={[Math.PI / 2, 0, 2.3]} scale={[0.02, 0.03, 0.03]}>
          <mesh material={materials.legs} geometry={nodes.Plane009_legs_0.geometry} />
        </group>
        <group position={[-0.01, 0.75, -0.02]} rotation={[1.43, 0.05, -0.15]} scale={[-0.01, -0.01, -0.01]}>
          <mesh material={materials.legs} geometry={nodes.Plane010_legs_0.geometry} />
        </group>
        <group position={[-0.2, 1.01, 0.21]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.legs} geometry={nodes.Plane011_legs_0.geometry} />
        </group>
        <group position={[0.22, 1.01, 0.18]} rotation={[Math.PI / 2, 0, 2.3]} scale={[0.02, 0.03, 0.03]}>
          <mesh material={materials.legs} geometry={nodes.Plane012_legs_0.geometry} />
        </group>
        <group position={[0.19, 1.01, -0.25]} rotation={[Math.PI / 2, 0, 2.3]} scale={[0.02, 0.03, 0.03]}>
          <mesh material={materials.legs} geometry={nodes.Plane013_legs_0.geometry} />
        </group>
        <group position={[0, 7.07, 0.29]} rotation={[Math.PI / 2, 0.02, -Math.PI / 2]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.details} geometry={nodes.Plane014_details_0.geometry} />
        </group>
        <group position={[0, 7.07, 0]} rotation={[Math.PI / 2, 0.02, -Math.PI / 2]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.details} geometry={nodes.Plane015_details_0.geometry} />
        </group>
        <group position={[0, 7.07, 0]} rotation={[Math.PI / 2, 0.02, -Math.PI / 2]} scale={[0.38, 0.38, 0.38]}>
          <mesh material={materials.details} geometry={nodes.Plane016_details_0.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./f9rocket.gltf')